### ISSUE TITLE
Missing RTL for message boxes and the About window

### ISSUE THREAD

**Issue by ItielMaN** [geekuninstaller/translations#11]
Missing RTL for message boxes:
![default](https://user-images.githubusercontent.com/18016656/31675913-a9e4a99e-b36e-11e7-836b-d0a0f1d6efa3.png)

Missing RTL for the About window:
![default](https://user-images.githubusercontent.com/18016656/31675926-b39d7286-b36e-11e7-812b-1e3904e965de.png)

**Comment by tomkoen** [comment]
Thank you, fixed. Will be in the next update
