### ISSUE TITLE
Your foolish software messed up my computer's registry

### ISSUE THREAD

**Issue by Paper-Folding** [geekuninstaller/translations#36]
I have uninstalled Edge Chromium use your foolish tool and end up with all my UWP installed on my computer corrupted, Microsoft Store included! Now I have to reinstall my whole OS. Goodbye, geek the shit.

**Comment by stuffbymax** [comment]
It sounds like the uninstallation process may have caused some unexpected issues with your Universal Windows Platform (UWP) apps, including the Microsoft Store. While Geek Uninstaller is generally a reliable tool for uninstalling software, sometimes unexpected conflicts or errors can occur, especially with system components like UWP apps.

**Comment by Paper-Folding** [comment]
@stuffbymax Seriously? After 3 years.... Geek uninstaller is actually good but I no longer need it.

**Comment by stuffbymax** [comment]
i find did your messege today
